/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateDoctorProfileDto,
    CreateDoctorProfileDtoFromJSON,
    CreateDoctorProfileDtoToJSON,
    CreateFamilyProfileInput,
    CreateFamilyProfileInputFromJSON,
    CreateFamilyProfileInputToJSON,
    CreateHealthCheckDto,
    CreateHealthCheckDtoFromJSON,
    CreateHealthCheckDtoToJSON,
    CreateMedicineDto,
    CreateMedicineDtoFromJSON,
    CreateMedicineDtoToJSON,
    DoctorProfile,
    DoctorProfileFromJSON,
    DoctorProfileToJSON,
    DoctorSignupInput,
    DoctorSignupInputFromJSON,
    DoctorSignupInputToJSON,
    HealthCheck,
    HealthCheckFromJSON,
    HealthCheckToJSON,
    InlineObject,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineResponse200,
    InlineResponse200FromJSON,
    InlineResponse200ToJSON,
    InlineResponse201,
    InlineResponse201FromJSON,
    InlineResponse201ToJSON,
    LoginInput,
    LoginInputFromJSON,
    LoginInputToJSON,
    Medicine,
    MedicineFromJSON,
    MedicineToJSON,
    SignupInput,
    SignupInputFromJSON,
    SignupInputToJSON,
    UpdateAvailabilityDto,
    UpdateAvailabilityDtoFromJSON,
    UpdateAvailabilityDtoToJSON,
    UpdateDoctorProfileDto,
    UpdateDoctorProfileDtoFromJSON,
    UpdateDoctorProfileDtoToJSON,
    UpdateHealthCheckDto,
    UpdateHealthCheckDtoFromJSON,
    UpdateHealthCheckDtoToJSON,
    UpdateMedicineDto,
    UpdateMedicineDtoFromJSON,
    UpdateMedicineDtoToJSON,
} from '../models';

export interface ApiAiChatPostRequest {
    inlineObject: InlineObject;
}

export interface ApiAppointmentsIdDeleteRequest {
    id: string;
}

export interface ApiAppointmentsIdStatusPatchRequest {
    id: string;
}

export interface ApiAuthDoctorSignupPostRequest {
    doctorSignupInput: DoctorSignupInput;
}

export interface ApiAuthLoginPostRequest {
    loginInput: LoginInput;
}

export interface ApiAuthSignupPostRequest {
    signupInput: SignupInput;
}

export interface ApiDoctorsAvailabilityPatchRequest {
    updateAvailabilityDto: UpdateAvailabilityDto;
}

export interface ApiDoctorsIdGetRequest {
    id: string;
}

export interface ApiDoctorsNearbyGetRequest {
    lat: number;
    lng: number;
    radius?: number;
    specialization?: string;
}

export interface ApiDoctorsProfilePatchRequest {
    updateDoctorProfileDto: UpdateDoctorProfileDto;
}

export interface ApiDoctorsProfilePostRequest {
    createDoctorProfileDto: CreateDoctorProfileDto;
}

export interface ApiFamilyPostRequest {
    createFamilyProfileInput: CreateFamilyProfileInput;
}

export interface ApiHealthChecksGetRequest {
    patientId: string;
}

export interface ApiHealthChecksIdDeleteRequest {
    id: string;
}

export interface ApiHealthChecksIdGetRequest {
    id: string;
}

export interface ApiHealthChecksIdPutRequest {
    id: string;
    updateHealthCheckDto: UpdateHealthCheckDto;
}

export interface ApiHealthChecksPostRequest {
    createHealthCheckDto: CreateHealthCheckDto;
}

export interface ApiHealthTrendPatientIdGetRequest {
    patientId: string;
    from?: string;
    to?: string;
}

export interface ApiMedicinesIdDeleteRequest {
    id: string;
}

export interface ApiMedicinesIdGetRequest {
    id: string;
}

export interface ApiMedicinesIdPutRequest {
    id: string;
    updateMedicineDto: UpdateMedicineDto;
}

export interface ApiMedicinesPostRequest {
    createMedicineDto: CreateMedicineDto;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Accepts a patientId and message history, fetches the patient\'s health data from the database, and streams a Gemini AI response as SSE events. Each event is `data: {\"text\":\"...\"}` and the stream ends with `data: [DONE]`. 
     * Stream an AI health assistant response
     */
    async apiAiChatPostRaw(requestParameters: ApiAiChatPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.inlineObject === null || requestParameters.inlineObject === undefined) {
            throw new runtime.RequiredError('inlineObject','Required parameter requestParameters.inlineObject was null or undefined when calling apiAiChatPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/ai/chat`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObjectToJSON(requestParameters.inlineObject),
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Accepts a patientId and message history, fetches the patient\'s health data from the database, and streams a Gemini AI response as SSE events. Each event is `data: {\"text\":\"...\"}` and the stream ends with `data: [DONE]`. 
     * Stream an AI health assistant response
     */
    async apiAiChatPost(requestParameters: ApiAiChatPostRequest, initOverrides?: RequestInit): Promise<string> {
        const response = await this.apiAiChatPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Cancel an appointment
     */
    async apiAppointmentsIdDeleteRaw(requestParameters: ApiAppointmentsIdDeleteRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiAppointmentsIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/appointments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Cancel an appointment
     */
    async apiAppointmentsIdDelete(requestParameters: ApiAppointmentsIdDeleteRequest, initOverrides?: RequestInit): Promise<void> {
        await this.apiAppointmentsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Update appointment status (doctors only)
     */
    async apiAppointmentsIdStatusPatchRaw(requestParameters: ApiAppointmentsIdStatusPatchRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiAppointmentsIdStatusPatch.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/appointments/{id}/status`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update appointment status (doctors only)
     */
    async apiAppointmentsIdStatusPatch(requestParameters: ApiAppointmentsIdStatusPatchRequest, initOverrides?: RequestInit): Promise<void> {
        await this.apiAppointmentsIdStatusPatchRaw(requestParameters, initOverrides);
    }

    /**
     * Get my appointments (patient gets own; doctor gets their schedule)
     */
    async apiAppointmentsMeGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/appointments/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get my appointments (patient gets own; doctor gets their schedule)
     */
    async apiAppointmentsMeGet(initOverrides?: RequestInit): Promise<void> {
        await this.apiAppointmentsMeGetRaw(initOverrides);
    }

    /**
     * Book an appointment (patients)
     */
    async apiAppointmentsPostRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/appointments`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Book an appointment (patients)
     */
    async apiAppointmentsPost(initOverrides?: RequestInit): Promise<void> {
        await this.apiAppointmentsPostRaw(initOverrides);
    }

    /**
     * Register a new doctor account
     */
    async apiAuthDoctorSignupPostRaw(requestParameters: ApiAuthDoctorSignupPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.doctorSignupInput === null || requestParameters.doctorSignupInput === undefined) {
            throw new runtime.RequiredError('doctorSignupInput','Required parameter requestParameters.doctorSignupInput was null or undefined when calling apiAuthDoctorSignupPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/auth/doctor/signup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DoctorSignupInputToJSON(requestParameters.doctorSignupInput),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Register a new doctor account
     */
    async apiAuthDoctorSignupPost(requestParameters: ApiAuthDoctorSignupPostRequest, initOverrides?: RequestInit): Promise<void> {
        await this.apiAuthDoctorSignupPostRaw(requestParameters, initOverrides);
    }

    /**
     * Login a user
     */
    async apiAuthLoginPostRaw(requestParameters: ApiAuthLoginPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.loginInput === null || requestParameters.loginInput === undefined) {
            throw new runtime.RequiredError('loginInput','Required parameter requestParameters.loginInput was null or undefined when calling apiAuthLoginPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginInputToJSON(requestParameters.loginInput),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Login a user
     */
    async apiAuthLoginPost(requestParameters: ApiAuthLoginPostRequest, initOverrides?: RequestInit): Promise<void> {
        await this.apiAuthLoginPostRaw(requestParameters, initOverrides);
    }

    /**
     * Register a new user
     */
    async apiAuthSignupPostRaw(requestParameters: ApiAuthSignupPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.signupInput === null || requestParameters.signupInput === undefined) {
            throw new runtime.RequiredError('signupInput','Required parameter requestParameters.signupInput was null or undefined when calling apiAuthSignupPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/auth/signup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignupInputToJSON(requestParameters.signupInput),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Register a new user
     */
    async apiAuthSignupPost(requestParameters: ApiAuthSignupPostRequest, initOverrides?: RequestInit): Promise<void> {
        await this.apiAuthSignupPostRaw(requestParameters, initOverrides);
    }

    /**
     * Update doctor availability slots
     */
    async apiDoctorsAvailabilityPatchRaw(requestParameters: ApiDoctorsAvailabilityPatchRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<DoctorProfile>> {
        if (requestParameters.updateAvailabilityDto === null || requestParameters.updateAvailabilityDto === undefined) {
            throw new runtime.RequiredError('updateAvailabilityDto','Required parameter requestParameters.updateAvailabilityDto was null or undefined when calling apiDoctorsAvailabilityPatch.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/doctors/availability`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAvailabilityDtoToJSON(requestParameters.updateAvailabilityDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DoctorProfileFromJSON(jsonValue));
    }

    /**
     * Update doctor availability slots
     */
    async apiDoctorsAvailabilityPatch(requestParameters: ApiDoctorsAvailabilityPatchRequest, initOverrides?: RequestInit): Promise<DoctorProfile> {
        const response = await this.apiDoctorsAvailabilityPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a doctor\'s public profile by profile id
     */
    async apiDoctorsIdGetRaw(requestParameters: ApiDoctorsIdGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiDoctorsIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/doctors/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get a doctor\'s public profile by profile id
     */
    async apiDoctorsIdGet(requestParameters: ApiDoctorsIdGetRequest, initOverrides?: RequestInit): Promise<void> {
        await this.apiDoctorsIdGetRaw(requestParameters, initOverrides);
    }

    /**
     * Get own doctor profile
     */
    async apiDoctorsMeGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/doctors/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get own doctor profile
     */
    async apiDoctorsMeGet(initOverrides?: RequestInit): Promise<void> {
        await this.apiDoctorsMeGetRaw(initOverrides);
    }

    /**
     * Find nearby available doctors
     */
    async apiDoctorsNearbyGetRaw(requestParameters: ApiDoctorsNearbyGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.lat === null || requestParameters.lat === undefined) {
            throw new runtime.RequiredError('lat','Required parameter requestParameters.lat was null or undefined when calling apiDoctorsNearbyGet.');
        }

        if (requestParameters.lng === null || requestParameters.lng === undefined) {
            throw new runtime.RequiredError('lng','Required parameter requestParameters.lng was null or undefined when calling apiDoctorsNearbyGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.lat !== undefined) {
            queryParameters['lat'] = requestParameters.lat;
        }

        if (requestParameters.lng !== undefined) {
            queryParameters['lng'] = requestParameters.lng;
        }

        if (requestParameters.radius !== undefined) {
            queryParameters['radius'] = requestParameters.radius;
        }

        if (requestParameters.specialization !== undefined) {
            queryParameters['specialization'] = requestParameters.specialization;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/doctors/nearby`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Find nearby available doctors
     */
    async apiDoctorsNearbyGet(requestParameters: ApiDoctorsNearbyGetRequest, initOverrides?: RequestInit): Promise<void> {
        await this.apiDoctorsNearbyGetRaw(requestParameters, initOverrides);
    }

    /**
     * Update own doctor profile fields
     */
    async apiDoctorsProfilePatchRaw(requestParameters: ApiDoctorsProfilePatchRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<DoctorProfile>> {
        if (requestParameters.updateDoctorProfileDto === null || requestParameters.updateDoctorProfileDto === undefined) {
            throw new runtime.RequiredError('updateDoctorProfileDto','Required parameter requestParameters.updateDoctorProfileDto was null or undefined when calling apiDoctorsProfilePatch.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/doctors/profile`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateDoctorProfileDtoToJSON(requestParameters.updateDoctorProfileDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DoctorProfileFromJSON(jsonValue));
    }

    /**
     * Update own doctor profile fields
     */
    async apiDoctorsProfilePatch(requestParameters: ApiDoctorsProfilePatchRequest, initOverrides?: RequestInit): Promise<DoctorProfile> {
        const response = await this.apiDoctorsProfilePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a doctor profile (doctors only)
     */
    async apiDoctorsProfilePostRaw(requestParameters: ApiDoctorsProfilePostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.createDoctorProfileDto === null || requestParameters.createDoctorProfileDto === undefined) {
            throw new runtime.RequiredError('createDoctorProfileDto','Required parameter requestParameters.createDoctorProfileDto was null or undefined when calling apiDoctorsProfilePost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/doctors/profile`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDoctorProfileDtoToJSON(requestParameters.createDoctorProfileDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a doctor profile (doctors only)
     */
    async apiDoctorsProfilePost(requestParameters: ApiDoctorsProfilePostRequest, initOverrides?: RequestInit): Promise<void> {
        await this.apiDoctorsProfilePostRaw(requestParameters, initOverrides);
    }

    /**
     * Get all elderly profiles for the current user
     */
    async apiFamilyGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<InlineResponse200>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/family`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse200FromJSON(jsonValue));
    }

    /**
     * Get all elderly profiles for the current user
     */
    async apiFamilyGet(initOverrides?: RequestInit): Promise<InlineResponse200> {
        const response = await this.apiFamilyGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create an elderly profile
     */
    async apiFamilyPostRaw(requestParameters: ApiFamilyPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<InlineResponse201>> {
        if (requestParameters.createFamilyProfileInput === null || requestParameters.createFamilyProfileInput === undefined) {
            throw new runtime.RequiredError('createFamilyProfileInput','Required parameter requestParameters.createFamilyProfileInput was null or undefined when calling apiFamilyPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/family`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateFamilyProfileInputToJSON(requestParameters.createFamilyProfileInput),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse201FromJSON(jsonValue));
    }

    /**
     * Create an elderly profile
     */
    async apiFamilyPost(requestParameters: ApiFamilyPostRequest, initOverrides?: RequestInit): Promise<InlineResponse201> {
        const response = await this.apiFamilyPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all health checks for a specific patient
     */
    async apiHealthChecksGetRaw(requestParameters: ApiHealthChecksGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<HealthCheck>>> {
        if (requestParameters.patientId === null || requestParameters.patientId === undefined) {
            throw new runtime.RequiredError('patientId','Required parameter requestParameters.patientId was null or undefined when calling apiHealthChecksGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.patientId !== undefined) {
            queryParameters['patient_id'] = requestParameters.patientId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/health-checks`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HealthCheckFromJSON));
    }

    /**
     * Get all health checks for a specific patient
     */
    async apiHealthChecksGet(requestParameters: ApiHealthChecksGetRequest, initOverrides?: RequestInit): Promise<Array<HealthCheck>> {
        const response = await this.apiHealthChecksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a health check
     */
    async apiHealthChecksIdDeleteRaw(requestParameters: ApiHealthChecksIdDeleteRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiHealthChecksIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/health-checks/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a health check
     */
    async apiHealthChecksIdDelete(requestParameters: ApiHealthChecksIdDeleteRequest, initOverrides?: RequestInit): Promise<void> {
        await this.apiHealthChecksIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get a health check by ID
     */
    async apiHealthChecksIdGetRaw(requestParameters: ApiHealthChecksIdGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<HealthCheck>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiHealthChecksIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/health-checks/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthCheckFromJSON(jsonValue));
    }

    /**
     * Get a health check by ID
     */
    async apiHealthChecksIdGet(requestParameters: ApiHealthChecksIdGetRequest, initOverrides?: RequestInit): Promise<HealthCheck> {
        const response = await this.apiHealthChecksIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a health check
     */
    async apiHealthChecksIdPutRaw(requestParameters: ApiHealthChecksIdPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<HealthCheck>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiHealthChecksIdPut.');
        }

        if (requestParameters.updateHealthCheckDto === null || requestParameters.updateHealthCheckDto === undefined) {
            throw new runtime.RequiredError('updateHealthCheckDto','Required parameter requestParameters.updateHealthCheckDto was null or undefined when calling apiHealthChecksIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/health-checks/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateHealthCheckDtoToJSON(requestParameters.updateHealthCheckDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthCheckFromJSON(jsonValue));
    }

    /**
     * Update a health check
     */
    async apiHealthChecksIdPut(requestParameters: ApiHealthChecksIdPutRequest, initOverrides?: RequestInit): Promise<HealthCheck> {
        const response = await this.apiHealthChecksIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new health check record
     */
    async apiHealthChecksPostRaw(requestParameters: ApiHealthChecksPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<HealthCheck>> {
        if (requestParameters.createHealthCheckDto === null || requestParameters.createHealthCheckDto === undefined) {
            throw new runtime.RequiredError('createHealthCheckDto','Required parameter requestParameters.createHealthCheckDto was null or undefined when calling apiHealthChecksPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/health-checks`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateHealthCheckDtoToJSON(requestParameters.createHealthCheckDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthCheckFromJSON(jsonValue));
    }

    /**
     * Create a new health check record
     */
    async apiHealthChecksPost(requestParameters: ApiHealthChecksPostRequest, initOverrides?: RequestInit): Promise<HealthCheck> {
        const response = await this.apiHealthChecksPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Full health trend summary for a patient (doctors only)
     */
    async apiHealthTrendPatientIdGetRaw(requestParameters: ApiHealthTrendPatientIdGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.patientId === null || requestParameters.patientId === undefined) {
            throw new runtime.RequiredError('patientId','Required parameter requestParameters.patientId was null or undefined when calling apiHealthTrendPatientIdGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.from !== undefined) {
            queryParameters['from'] = requestParameters.from;
        }

        if (requestParameters.to !== undefined) {
            queryParameters['to'] = requestParameters.to;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/health-trend/{patientId}`.replace(`{${"patientId"}}`, encodeURIComponent(String(requestParameters.patientId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Full health trend summary for a patient (doctors only)
     */
    async apiHealthTrendPatientIdGet(requestParameters: ApiHealthTrendPatientIdGetRequest, initOverrides?: RequestInit): Promise<void> {
        await this.apiHealthTrendPatientIdGetRaw(requestParameters, initOverrides);
    }

    /**
     * Get all medicines
     */
    async apiMedicinesGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Medicine>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/medicines`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MedicineFromJSON));
    }

    /**
     * Get all medicines
     */
    async apiMedicinesGet(initOverrides?: RequestInit): Promise<Array<Medicine>> {
        const response = await this.apiMedicinesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Delete a medicine
     */
    async apiMedicinesIdDeleteRaw(requestParameters: ApiMedicinesIdDeleteRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiMedicinesIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/medicines/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a medicine
     */
    async apiMedicinesIdDelete(requestParameters: ApiMedicinesIdDeleteRequest, initOverrides?: RequestInit): Promise<void> {
        await this.apiMedicinesIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get a medicine by id
     */
    async apiMedicinesIdGetRaw(requestParameters: ApiMedicinesIdGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Medicine>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiMedicinesIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/medicines/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MedicineFromJSON(jsonValue));
    }

    /**
     * Get a medicine by id
     */
    async apiMedicinesIdGet(requestParameters: ApiMedicinesIdGetRequest, initOverrides?: RequestInit): Promise<Medicine> {
        const response = await this.apiMedicinesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a medicine
     */
    async apiMedicinesIdPutRaw(requestParameters: ApiMedicinesIdPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Medicine>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiMedicinesIdPut.');
        }

        if (requestParameters.updateMedicineDto === null || requestParameters.updateMedicineDto === undefined) {
            throw new runtime.RequiredError('updateMedicineDto','Required parameter requestParameters.updateMedicineDto was null or undefined when calling apiMedicinesIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/medicines/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMedicineDtoToJSON(requestParameters.updateMedicineDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MedicineFromJSON(jsonValue));
    }

    /**
     * Update a medicine
     */
    async apiMedicinesIdPut(requestParameters: ApiMedicinesIdPutRequest, initOverrides?: RequestInit): Promise<Medicine> {
        const response = await this.apiMedicinesIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new medicine
     */
    async apiMedicinesPostRaw(requestParameters: ApiMedicinesPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Medicine>> {
        if (requestParameters.createMedicineDto === null || requestParameters.createMedicineDto === undefined) {
            throw new runtime.RequiredError('createMedicineDto','Required parameter requestParameters.createMedicineDto was null or undefined when calling apiMedicinesPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/medicines`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMedicineDtoToJSON(requestParameters.createMedicineDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MedicineFromJSON(jsonValue));
    }

    /**
     * Create a new medicine
     */
    async apiMedicinesPost(requestParameters: ApiMedicinesPostRequest, initOverrides?: RequestInit): Promise<Medicine> {
        const response = await this.apiMedicinesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
