/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiAiChatMessages
 */
export interface ApiAiChatMessages {
    /**
     * 
     * @type {string}
     * @memberof ApiAiChatMessages
     */
    role?: ApiAiChatMessagesRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiAiChatMessages
     */
    content?: string;
}

/**
* @export
* @enum {string}
*/
export enum ApiAiChatMessagesRoleEnum {
    User = 'user',
    Assistant = 'assistant'
}

export function ApiAiChatMessagesFromJSON(json: any): ApiAiChatMessages {
    return ApiAiChatMessagesFromJSONTyped(json, false);
}

export function ApiAiChatMessagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAiChatMessages {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'role': !exists(json, 'role') ? undefined : json['role'],
        'content': !exists(json, 'content') ? undefined : json['content'],
    };
}

export function ApiAiChatMessagesToJSON(value?: ApiAiChatMessages | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role': value.role,
        'content': value.content,
    };
}

