/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Appointment
 */
export interface Appointment {
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    patientId: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    doctorProfileId: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    slotId: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    status: AppointmentStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    mode: AppointmentModeEnum;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    updatedAt: string;
}

/**
* @export
* @enum {string}
*/
export enum AppointmentStatusEnum {
    Pending = 'pending',
    Confirmed = 'confirmed',
    Cancelled = 'cancelled',
    Completed = 'completed'
}/**
* @export
* @enum {string}
*/
export enum AppointmentModeEnum {
    InPerson = 'in-person',
    Video = 'video',
    Phone = 'phone'
}

export function AppointmentFromJSON(json: any): Appointment {
    return AppointmentFromJSONTyped(json, false);
}

export function AppointmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Appointment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'patientId': json['patient_id'],
        'doctorProfileId': json['doctor_profile_id'],
        'slotId': json['slot_id'],
        'date': json['date'],
        'status': json['status'],
        'mode': json['mode'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function AppointmentToJSON(value?: Appointment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'patient_id': value.patientId,
        'doctor_profile_id': value.doctorProfileId,
        'slot_id': value.slotId,
        'date': value.date,
        'status': value.status,
        'mode': value.mode,
        'notes': value.notes,
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
    };
}

