/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMedicineDto
 */
export interface CreateMedicineDto {
    /**
     * 
     * @type {string}
     * @memberof CreateMedicineDto
     */
    patientId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMedicineDto
     */
    medicineName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMedicineDto
     */
    medicineType: CreateMedicineDtoMedicineTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateMedicineDto
     */
    dosage: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMedicineDto
     */
    strength?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMedicineDto
     */
    frequency: CreateMedicineDtoFrequencyEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateMedicineDto
     */
    timing: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateMedicineDto
     */
    startDate: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMedicineDto
     */
    endDate?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateMedicineDto
     */
    reminderEnabled: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateMedicineDto
     */
    reminderTimes: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CreateMedicineDto
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateMedicineDto
     */
    doctorName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMedicineDto
     */
    prescriptionNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMedicineDto
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMedicineDto
     */
    status: CreateMedicineDtoStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum CreateMedicineDtoMedicineTypeEnum {
    Tablet = 'Tablet',
    Capsule = 'Capsule',
    Syrup = 'Syrup',
    Injection = 'Injection',
    Drops = 'Drops',
    Cream = 'Cream',
    Other = 'Other'
}/**
* @export
* @enum {string}
*/
export enum CreateMedicineDtoFrequencyEnum {
    OnceDaily = 'Once Daily',
    TwiceDaily = 'Twice Daily',
    ThreeTimesDaily = 'Three Times Daily',
    FourTimesDaily = 'Four Times Daily',
    Every6Hours = 'Every 6 Hours',
    Weekly = 'Weekly',
    Custom = 'Custom'
}/**
* @export
* @enum {string}
*/
export enum CreateMedicineDtoStatusEnum {
    Active = 'Active',
    Completed = 'Completed',
    Upcoming = 'Upcoming',
    Expired = 'Expired'
}

export function CreateMedicineDtoFromJSON(json: any): CreateMedicineDto {
    return CreateMedicineDtoFromJSONTyped(json, false);
}

export function CreateMedicineDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMedicineDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientId': json['patient_id'],
        'medicineName': json['medicine_name'],
        'medicineType': json['medicine_type'],
        'dosage': json['dosage'],
        'strength': !exists(json, 'strength') ? undefined : json['strength'],
        'frequency': json['frequency'],
        'timing': json['timing'],
        'startDate': json['start_date'],
        'endDate': !exists(json, 'end_date') ? undefined : json['end_date'],
        'reminderEnabled': json['reminder_enabled'],
        'reminderTimes': json['reminder_times'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
        'doctorName': !exists(json, 'doctor_name') ? undefined : json['doctor_name'],
        'prescriptionNumber': !exists(json, 'prescription_number') ? undefined : json['prescription_number'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'status': json['status'],
    };
}

export function CreateMedicineDtoToJSON(value?: CreateMedicineDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patient_id': value.patientId,
        'medicine_name': value.medicineName,
        'medicine_type': value.medicineType,
        'dosage': value.dosage,
        'strength': value.strength,
        'frequency': value.frequency,
        'timing': value.timing,
        'start_date': value.startDate,
        'end_date': value.endDate,
        'reminder_enabled': value.reminderEnabled,
        'reminder_times': value.reminderTimes,
        'quantity': value.quantity,
        'doctor_name': value.doctorName,
        'prescription_number': value.prescriptionNumber,
        'notes': value.notes,
        'status': value.status,
    };
}

