/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateHealthCheckDto
 */
export interface CreateHealthCheckDto {
    /**
     * 
     * @type {string}
     * @memberof CreateHealthCheckDto
     */
    patientId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateHealthCheckDto
     */
    recordedById?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateHealthCheckDto
     */
    sugarLevel?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateHealthCheckDto
     */
    weight?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateHealthCheckDto
     */
    bloodPressure?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateHealthCheckDto
     */
    bloodLevel?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateHealthCheckDto
     */
    bmi?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateHealthCheckDto
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof CreateHealthCheckDto
     */
    notes?: string;
}

export function CreateHealthCheckDtoFromJSON(json: any): CreateHealthCheckDto {
    return CreateHealthCheckDtoFromJSONTyped(json, false);
}

export function CreateHealthCheckDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateHealthCheckDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientId': json['patient_id'],
        'recordedById': !exists(json, 'recorded_by_id') ? undefined : json['recorded_by_id'],
        'sugarLevel': !exists(json, 'sugar_level') ? undefined : json['sugar_level'],
        'weight': !exists(json, 'weight') ? undefined : json['weight'],
        'bloodPressure': !exists(json, 'blood_pressure') ? undefined : json['blood_pressure'],
        'bloodLevel': !exists(json, 'blood_level') ? undefined : json['blood_level'],
        'bmi': !exists(json, 'bmi') ? undefined : json['bmi'],
        'date': json['date'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
    };
}

export function CreateHealthCheckDtoToJSON(value?: CreateHealthCheckDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patient_id': value.patientId,
        'recorded_by_id': value.recordedById,
        'sugar_level': value.sugarLevel,
        'weight': value.weight,
        'blood_pressure': value.bloodPressure,
        'blood_level': value.bloodLevel,
        'bmi': value.bmi,
        'date': value.date,
        'notes': value.notes,
    };
}

