/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFamilyProfileInputEmergencyContacts
 */
export interface CreateFamilyProfileInputEmergencyContacts {
    /**
     * 
     * @type {string}
     * @memberof CreateFamilyProfileInputEmergencyContacts
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFamilyProfileInputEmergencyContacts
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFamilyProfileInputEmergencyContacts
     */
    relation: string;
}

export function CreateFamilyProfileInputEmergencyContactsFromJSON(json: any): CreateFamilyProfileInputEmergencyContacts {
    return CreateFamilyProfileInputEmergencyContactsFromJSONTyped(json, false);
}

export function CreateFamilyProfileInputEmergencyContactsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFamilyProfileInputEmergencyContacts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'phone': json['phone'],
        'relation': json['relation'],
    };
}

export function CreateFamilyProfileInputEmergencyContactsToJSON(value?: CreateFamilyProfileInputEmergencyContacts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'phone': value.phone,
        'relation': value.relation,
    };
}

