/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateFamilyProfileInputEmergencyContacts,
    CreateFamilyProfileInputEmergencyContactsFromJSON,
    CreateFamilyProfileInputEmergencyContactsFromJSONTyped,
    CreateFamilyProfileInputEmergencyContactsToJSON,
} from './CreateFamilyProfileInputEmergencyContacts';

/**
 * 
 * @export
 * @interface CreateFamilyProfileInput
 */
export interface CreateFamilyProfileInput {
    /**
     * 
     * @type {string}
     * @memberof CreateFamilyProfileInput
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFamilyProfileInput
     */
    birthDate: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFamilyProfileInput
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFamilyProfileInput
     */
    password?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateFamilyProfileInput
     */
    medicalConditions: Array<string>;
    /**
     * 
     * @type {Array<CreateFamilyProfileInputEmergencyContacts>}
     * @memberof CreateFamilyProfileInput
     */
    emergencyContacts: Array<CreateFamilyProfileInputEmergencyContacts>;
}

export function CreateFamilyProfileInputFromJSON(json: any): CreateFamilyProfileInput {
    return CreateFamilyProfileInputFromJSONTyped(json, false);
}

export function CreateFamilyProfileInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFamilyProfileInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fullName': json['fullName'],
        'birthDate': json['birthDate'],
        'email': json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'medicalConditions': json['medicalConditions'],
        'emergencyContacts': ((json['emergencyContacts'] as Array<any>).map(CreateFamilyProfileInputEmergencyContactsFromJSON)),
    };
}

export function CreateFamilyProfileInputToJSON(value?: CreateFamilyProfileInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fullName': value.fullName,
        'birthDate': value.birthDate,
        'email': value.email,
        'password': value.password,
        'medicalConditions': value.medicalConditions,
        'emergencyContacts': ((value.emergencyContacts as Array<any>).map(CreateFamilyProfileInputEmergencyContactsToJSON)),
    };
}

