/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PrescriptionMedications,
    PrescriptionMedicationsFromJSON,
    PrescriptionMedicationsFromJSONTyped,
    PrescriptionMedicationsToJSON,
} from './PrescriptionMedications';

/**
 * 
 * @export
 * @interface CreatePrescriptionDto
 */
export interface CreatePrescriptionDto {
    /**
     * 
     * @type {string}
     * @memberof CreatePrescriptionDto
     */
    patientId: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePrescriptionDto
     */
    appointmentId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePrescriptionDto
     */
    diagnosis: string;
    /**
     * 
     * @type {Array<PrescriptionMedications>}
     * @memberof CreatePrescriptionDto
     */
    medications: Array<PrescriptionMedications>;
    /**
     * 
     * @type {string}
     * @memberof CreatePrescriptionDto
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePrescriptionDto
     */
    issuedAt: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePrescriptionDto
     */
    validUntil?: string;
}

export function CreatePrescriptionDtoFromJSON(json: any): CreatePrescriptionDto {
    return CreatePrescriptionDtoFromJSONTyped(json, false);
}

export function CreatePrescriptionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePrescriptionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientId': json['patient_id'],
        'appointmentId': !exists(json, 'appointment_id') ? undefined : json['appointment_id'],
        'diagnosis': json['diagnosis'],
        'medications': ((json['medications'] as Array<any>).map(PrescriptionMedicationsFromJSON)),
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'issuedAt': json['issued_at'],
        'validUntil': !exists(json, 'valid_until') ? undefined : json['valid_until'],
    };
}

export function CreatePrescriptionDtoToJSON(value?: CreatePrescriptionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patient_id': value.patientId,
        'appointment_id': value.appointmentId,
        'diagnosis': value.diagnosis,
        'medications': ((value.medications as Array<any>).map(PrescriptionMedicationsToJSON)),
        'notes': value.notes,
        'issued_at': value.issuedAt,
        'valid_until': value.validUntil,
    };
}

