/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DoctorProfileAvailability,
    DoctorProfileAvailabilityFromJSON,
    DoctorProfileAvailabilityFromJSONTyped,
    DoctorProfileAvailabilityToJSON,
} from './DoctorProfileAvailability';
import {
    DoctorProfileLocation,
    DoctorProfileLocationFromJSON,
    DoctorProfileLocationFromJSONTyped,
    DoctorProfileLocationToJSON,
} from './DoctorProfileLocation';

/**
 * 
 * @export
 * @interface CreateDoctorProfileDto
 */
export interface CreateDoctorProfileDto {
    /**
     * 
     * @type {string}
     * @memberof CreateDoctorProfileDto
     */
    specialization: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDoctorProfileDto
     */
    licenseNumber: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDoctorProfileDto
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDoctorProfileDto
     */
    bio?: string;
    /**
     * 
     * @type {DoctorProfileLocation}
     * @memberof CreateDoctorProfileDto
     */
    location: DoctorProfileLocation;
    /**
     * 
     * @type {Array<DoctorProfileAvailability>}
     * @memberof CreateDoctorProfileDto
     */
    availability: Array<DoctorProfileAvailability>;
    /**
     * 
     * @type {boolean}
     * @memberof CreateDoctorProfileDto
     */
    isAvailableForEmergency: boolean;
}

export function CreateDoctorProfileDtoFromJSON(json: any): CreateDoctorProfileDto {
    return CreateDoctorProfileDtoFromJSONTyped(json, false);
}

export function CreateDoctorProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDoctorProfileDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'specialization': json['specialization'],
        'licenseNumber': json['license_number'],
        'phone': json['phone'],
        'bio': !exists(json, 'bio') ? undefined : json['bio'],
        'location': DoctorProfileLocationFromJSON(json['location']),
        'availability': ((json['availability'] as Array<any>).map(DoctorProfileAvailabilityFromJSON)),
        'isAvailableForEmergency': json['is_available_for_emergency'],
    };
}

export function CreateDoctorProfileDtoToJSON(value?: CreateDoctorProfileDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'specialization': value.specialization,
        'license_number': value.licenseNumber,
        'phone': value.phone,
        'bio': value.bio,
        'location': DoctorProfileLocationToJSON(value.location),
        'availability': ((value.availability as Array<any>).map(DoctorProfileAvailabilityToJSON)),
        'is_available_for_emergency': value.isAvailableForEmergency,
    };
}

