/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DoctorProfileLocation,
    DoctorProfileLocationFromJSON,
    DoctorProfileLocationFromJSONTyped,
    DoctorProfileLocationToJSON,
} from './DoctorProfileLocation';

/**
 * 
 * @export
 * @interface CreateEmergencyDto
 */
export interface CreateEmergencyDto {
    /**
     * 
     * @type {DoctorProfileLocation}
     * @memberof CreateEmergencyDto
     */
    location: DoctorProfileLocation;
    /**
     * 
     * @type {string}
     * @memberof CreateEmergencyDto
     */
    description?: string;
}

export function CreateEmergencyDtoFromJSON(json: any): CreateEmergencyDto {
    return CreateEmergencyDtoFromJSONTyped(json, false);
}

export function CreateEmergencyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEmergencyDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'location': DoctorProfileLocationFromJSON(json['location']),
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function CreateEmergencyDtoToJSON(value?: CreateEmergencyDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'location': DoctorProfileLocationToJSON(value.location),
        'description': value.description,
    };
}

