/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAppointmentDto
 */
export interface CreateAppointmentDto {
    /**
     * 
     * @type {string}
     * @memberof CreateAppointmentDto
     */
    doctorProfileId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAppointmentDto
     */
    slotId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAppointmentDto
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAppointmentDto
     */
    mode: CreateAppointmentDtoModeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateAppointmentDto
     */
    notes?: string;
}

/**
* @export
* @enum {string}
*/
export enum CreateAppointmentDtoModeEnum {
    InPerson = 'in-person',
    Video = 'video',
    Phone = 'phone'
}

export function CreateAppointmentDtoFromJSON(json: any): CreateAppointmentDto {
    return CreateAppointmentDtoFromJSONTyped(json, false);
}

export function CreateAppointmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAppointmentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'doctorProfileId': json['doctor_profile_id'],
        'slotId': json['slot_id'],
        'date': json['date'],
        'mode': json['mode'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
    };
}

export function CreateAppointmentDtoToJSON(value?: CreateAppointmentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'doctor_profile_id': value.doctorProfileId,
        'slot_id': value.slotId,
        'date': value.date,
        'mode': value.mode,
        'notes': value.notes,
    };
}

