/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DoctorProfileLocation
 */
export interface DoctorProfileLocation {
    /**
     * 
     * @type {string}
     * @memberof DoctorProfileLocation
     */
    type: DoctorProfileLocationTypeEnum;
    /**
     * 
     * @type {Array<number>}
     * @memberof DoctorProfileLocation
     */
    coordinates: Array<number>;
}

/**
* @export
* @enum {string}
*/
export enum DoctorProfileLocationTypeEnum {
    Point = 'Point'
}

export function DoctorProfileLocationFromJSON(json: any): DoctorProfileLocation {
    return DoctorProfileLocationFromJSONTyped(json, false);
}

export function DoctorProfileLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoctorProfileLocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'coordinates': json['coordinates'],
    };
}

export function DoctorProfileLocationToJSON(value?: DoctorProfileLocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'coordinates': value.coordinates,
    };
}

