/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DoctorProfileAvailability
 */
export interface DoctorProfileAvailability {
    /**
     * 
     * @type {string}
     * @memberof DoctorProfileAvailability
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof DoctorProfileAvailability
     */
    dayOfWeek: number;
    /**
     * 
     * @type {string}
     * @memberof DoctorProfileAvailability
     */
    startTime: string;
    /**
     * 
     * @type {string}
     * @memberof DoctorProfileAvailability
     */
    endTime: string;
    /**
     * 
     * @type {boolean}
     * @memberof DoctorProfileAvailability
     */
    isBooked: boolean;
}

export function DoctorProfileAvailabilityFromJSON(json: any): DoctorProfileAvailability {
    return DoctorProfileAvailabilityFromJSONTyped(json, false);
}

export function DoctorProfileAvailabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoctorProfileAvailability {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'dayOfWeek': json['day_of_week'],
        'startTime': json['start_time'],
        'endTime': json['end_time'],
        'isBooked': json['is_booked'],
    };
}

export function DoctorProfileAvailabilityToJSON(value?: DoctorProfileAvailability | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'day_of_week': value.dayOfWeek,
        'start_time': value.startTime,
        'end_time': value.endTime,
        'is_booked': value.isBooked,
    };
}

