/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DoctorProfileAvailability,
    DoctorProfileAvailabilityFromJSON,
    DoctorProfileAvailabilityFromJSONTyped,
    DoctorProfileAvailabilityToJSON,
} from './DoctorProfileAvailability';
import {
    DoctorProfileLocation,
    DoctorProfileLocationFromJSON,
    DoctorProfileLocationFromJSONTyped,
    DoctorProfileLocationToJSON,
} from './DoctorProfileLocation';

/**
 * 
 * @export
 * @interface DoctorProfile
 */
export interface DoctorProfile {
    /**
     * 
     * @type {string}
     * @memberof DoctorProfile
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DoctorProfile
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof DoctorProfile
     */
    specialization: string;
    /**
     * 
     * @type {string}
     * @memberof DoctorProfile
     */
    licenseNumber: string;
    /**
     * 
     * @type {string}
     * @memberof DoctorProfile
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof DoctorProfile
     */
    bio?: string;
    /**
     * 
     * @type {DoctorProfileLocation}
     * @memberof DoctorProfile
     */
    location: DoctorProfileLocation;
    /**
     * 
     * @type {Array<DoctorProfileAvailability>}
     * @memberof DoctorProfile
     */
    availability: Array<DoctorProfileAvailability>;
    /**
     * 
     * @type {boolean}
     * @memberof DoctorProfile
     */
    isAvailableForEmergency: boolean;
    /**
     * 
     * @type {string}
     * @memberof DoctorProfile
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof DoctorProfile
     */
    updatedAt: string;
}

export function DoctorProfileFromJSON(json: any): DoctorProfile {
    return DoctorProfileFromJSONTyped(json, false);
}

export function DoctorProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoctorProfile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'specialization': json['specialization'],
        'licenseNumber': json['license_number'],
        'phone': json['phone'],
        'bio': !exists(json, 'bio') ? undefined : json['bio'],
        'location': DoctorProfileLocationFromJSON(json['location']),
        'availability': ((json['availability'] as Array<any>).map(DoctorProfileAvailabilityFromJSON)),
        'isAvailableForEmergency': json['is_available_for_emergency'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function DoctorProfileToJSON(value?: DoctorProfile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'user_id': value.userId,
        'specialization': value.specialization,
        'license_number': value.licenseNumber,
        'phone': value.phone,
        'bio': value.bio,
        'location': DoctorProfileLocationToJSON(value.location),
        'availability': ((value.availability as Array<any>).map(DoctorProfileAvailabilityToJSON)),
        'is_available_for_emergency': value.isAvailableForEmergency,
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
    };
}

