/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DoctorSignupInput
 */
export interface DoctorSignupInput {
    /**
     * 
     * @type {string}
     * @memberof DoctorSignupInput
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof DoctorSignupInput
     */
    birthdate: string;
    /**
     * 
     * @type {string}
     * @memberof DoctorSignupInput
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof DoctorSignupInput
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof DoctorSignupInput
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof DoctorSignupInput
     */
    licenseNumber: string;
    /**
     * 
     * @type {string}
     * @memberof DoctorSignupInput
     */
    specialization: string;
}

export function DoctorSignupInputFromJSON(json: any): DoctorSignupInput {
    return DoctorSignupInputFromJSONTyped(json, false);
}

export function DoctorSignupInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoctorSignupInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fullName': json['fullName'],
        'birthdate': json['birthdate'],
        'email': json['email'],
        'password': json['password'],
        'phone': json['phone'],
        'licenseNumber': json['licenseNumber'],
        'specialization': json['specialization'],
    };
}

export function DoctorSignupInputToJSON(value?: DoctorSignupInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fullName': value.fullName,
        'birthdate': value.birthdate,
        'email': value.email,
        'password': value.password,
        'phone': value.phone,
        'licenseNumber': value.licenseNumber,
        'specialization': value.specialization,
    };
}

