/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DoctorProfileLocation,
    DoctorProfileLocationFromJSON,
    DoctorProfileLocationFromJSONTyped,
    DoctorProfileLocationToJSON,
} from './DoctorProfileLocation';

/**
 * 
 * @export
 * @interface EmergencyRequest
 */
export interface EmergencyRequest {
    /**
     * 
     * @type {string}
     * @memberof EmergencyRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EmergencyRequest
     */
    patientId: string;
    /**
     * 
     * @type {DoctorProfileLocation}
     * @memberof EmergencyRequest
     */
    location: DoctorProfileLocation;
    /**
     * 
     * @type {string}
     * @memberof EmergencyRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof EmergencyRequest
     */
    status: EmergencyRequestStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof EmergencyRequest
     */
    acceptedByDoctorId?: string;
    /**
     * 
     * @type {string}
     * @memberof EmergencyRequest
     */
    acceptedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof EmergencyRequest
     */
    resolvedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof EmergencyRequest
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof EmergencyRequest
     */
    updatedAt: string;
}

/**
* @export
* @enum {string}
*/
export enum EmergencyRequestStatusEnum {
    Open = 'open',
    Accepted = 'accepted',
    Resolved = 'resolved',
    Cancelled = 'cancelled'
}

export function EmergencyRequestFromJSON(json: any): EmergencyRequest {
    return EmergencyRequestFromJSONTyped(json, false);
}

export function EmergencyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmergencyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'patientId': json['patient_id'],
        'location': DoctorProfileLocationFromJSON(json['location']),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'status': json['status'],
        'acceptedByDoctorId': !exists(json, 'accepted_by_doctor_id') ? undefined : json['accepted_by_doctor_id'],
        'acceptedAt': !exists(json, 'accepted_at') ? undefined : json['accepted_at'],
        'resolvedAt': !exists(json, 'resolved_at') ? undefined : json['resolved_at'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function EmergencyRequestToJSON(value?: EmergencyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'patient_id': value.patientId,
        'location': DoctorProfileLocationToJSON(value.location),
        'description': value.description,
        'status': value.status,
        'accepted_by_doctor_id': value.acceptedByDoctorId,
        'accepted_at': value.acceptedAt,
        'resolved_at': value.resolvedAt,
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
    };
}

