/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FamilyProfile
 */
export interface FamilyProfile {
    /**
     * 
     * @type {string}
     * @memberof FamilyProfile
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FamilyProfile
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof FamilyProfile
     */
    linkedToUserId: string;
    /**
     * 
     * @type {string}
     * @memberof FamilyProfile
     */
    medicalCondition: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof FamilyProfile
     */
    emergencyContacts: Array<string>;
}

export function FamilyProfileFromJSON(json: any): FamilyProfile {
    return FamilyProfileFromJSONTyped(json, false);
}

export function FamilyProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): FamilyProfile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'linkedToUserId': json['linkedToUserId'],
        'medicalCondition': json['medicalCondition'],
        'emergencyContacts': json['emergencyContacts'],
    };
}

export function FamilyProfileToJSON(value?: FamilyProfile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userId': value.userId,
        'linkedToUserId': value.linkedToUserId,
        'medicalCondition': value.medicalCondition,
        'emergencyContacts': value.emergencyContacts,
    };
}

