/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthCheck
 */
export interface HealthCheck {
    /**
     * 
     * @type {string}
     * @memberof HealthCheck
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof HealthCheck
     */
    patientId: string;
    /**
     * 
     * @type {string}
     * @memberof HealthCheck
     */
    recordedById?: string;
    /**
     * 
     * @type {number}
     * @memberof HealthCheck
     */
    sugarLevel?: number;
    /**
     * 
     * @type {number}
     * @memberof HealthCheck
     */
    weight?: number;
    /**
     * 
     * @type {string}
     * @memberof HealthCheck
     */
    bloodPressure?: string;
    /**
     * 
     * @type {string}
     * @memberof HealthCheck
     */
    bloodLevel?: string;
    /**
     * 
     * @type {number}
     * @memberof HealthCheck
     */
    bmi?: number;
    /**
     * 
     * @type {string}
     * @memberof HealthCheck
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof HealthCheck
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof HealthCheck
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof HealthCheck
     */
    updatedAt: string;
}

export function HealthCheckFromJSON(json: any): HealthCheck {
    return HealthCheckFromJSONTyped(json, false);
}

export function HealthCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheck {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'patientId': json['patient_id'],
        'recordedById': !exists(json, 'recorded_by_id') ? undefined : json['recorded_by_id'],
        'sugarLevel': !exists(json, 'sugar_level') ? undefined : json['sugar_level'],
        'weight': !exists(json, 'weight') ? undefined : json['weight'],
        'bloodPressure': !exists(json, 'blood_pressure') ? undefined : json['blood_pressure'],
        'bloodLevel': !exists(json, 'blood_level') ? undefined : json['blood_level'],
        'bmi': !exists(json, 'bmi') ? undefined : json['bmi'],
        'date': json['date'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function HealthCheckToJSON(value?: HealthCheck | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'patient_id': value.patientId,
        'recorded_by_id': value.recordedById,
        'sugar_level': value.sugarLevel,
        'weight': value.weight,
        'blood_pressure': value.bloodPressure,
        'blood_level': value.bloodLevel,
        'bmi': value.bmi,
        'date': value.date,
        'notes': value.notes,
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
    };
}

