/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApiAiChatMessages,
    ApiAiChatMessagesFromJSON,
    ApiAiChatMessagesFromJSONTyped,
    ApiAiChatMessagesToJSON,
} from './ApiAiChatMessages';

/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    patientId: string;
    /**
     * 
     * @type {Array<ApiAiChatMessages>}
     * @memberof InlineObject
     */
    messages: Array<ApiAiChatMessages>;
}

export function InlineObjectFromJSON(json: any): InlineObject {
    return InlineObjectFromJSONTyped(json, false);
}

export function InlineObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientId': json['patientId'],
        'messages': ((json['messages'] as Array<any>).map(ApiAiChatMessagesFromJSON)),
    };
}

export function InlineObjectToJSON(value?: InlineObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patientId': value.patientId,
        'messages': ((value.messages as Array<any>).map(ApiAiChatMessagesToJSON)),
    };
}

