/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FamilyProfile,
    FamilyProfileFromJSON,
    FamilyProfileFromJSONTyped,
    FamilyProfileToJSON,
} from './FamilyProfile';

/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {Array<FamilyProfile>}
     * @memberof InlineResponse200
     */
    profiles?: Array<FamilyProfile>;
}

export function InlineResponse200FromJSON(json: any): InlineResponse200 {
    return InlineResponse200FromJSONTyped(json, false);
}

export function InlineResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'profiles': !exists(json, 'profiles') ? undefined : ((json['profiles'] as Array<any>).map(FamilyProfileFromJSON)),
    };
}

export function InlineResponse200ToJSON(value?: InlineResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'profiles': value.profiles === undefined ? undefined : ((value.profiles as Array<any>).map(FamilyProfileToJSON)),
    };
}

