/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JwtPayload
 */
export interface JwtPayload {
    /**
     * 
     * @type {string}
     * @memberof JwtPayload
     */
    sub: string;
    /**
     * 
     * @type {string}
     * @memberof JwtPayload
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof JwtPayload
     */
    role?: JwtPayloadRoleEnum;
}

/**
* @export
* @enum {string}
*/
export enum JwtPayloadRoleEnum {
    Normal = 'normal',
    Family = 'family',
    Doctor = 'doctor'
}

export function JwtPayloadFromJSON(json: any): JwtPayload {
    return JwtPayloadFromJSONTyped(json, false);
}

export function JwtPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sub': json['sub'],
        'email': json['email'],
        'role': !exists(json, 'role') ? undefined : json['role'],
    };
}

export function JwtPayloadToJSON(value?: JwtPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sub': value.sub,
        'email': value.email,
        'role': value.role,
    };
}

