/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrescriptionMedications
 */
export interface PrescriptionMedications {
    /**
     * 
     * @type {string}
     * @memberof PrescriptionMedications
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PrescriptionMedications
     */
    dosage: string;
    /**
     * 
     * @type {string}
     * @memberof PrescriptionMedications
     */
    frequency: string;
    /**
     * 
     * @type {string}
     * @memberof PrescriptionMedications
     */
    duration: string;
    /**
     * 
     * @type {string}
     * @memberof PrescriptionMedications
     */
    instructions?: string;
}

export function PrescriptionMedicationsFromJSON(json: any): PrescriptionMedications {
    return PrescriptionMedicationsFromJSONTyped(json, false);
}

export function PrescriptionMedicationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrescriptionMedications {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'dosage': json['dosage'],
        'frequency': json['frequency'],
        'duration': json['duration'],
        'instructions': !exists(json, 'instructions') ? undefined : json['instructions'],
    };
}

export function PrescriptionMedicationsToJSON(value?: PrescriptionMedications | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'dosage': value.dosage,
        'frequency': value.frequency,
        'duration': value.duration,
        'instructions': value.instructions,
    };
}

