/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PrescriptionMedications,
    PrescriptionMedicationsFromJSON,
    PrescriptionMedicationsFromJSONTyped,
    PrescriptionMedicationsToJSON,
} from './PrescriptionMedications';

/**
 * 
 * @export
 * @interface Prescription
 */
export interface Prescription {
    /**
     * 
     * @type {string}
     * @memberof Prescription
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Prescription
     */
    patientId: string;
    /**
     * 
     * @type {string}
     * @memberof Prescription
     */
    doctorId: string;
    /**
     * 
     * @type {string}
     * @memberof Prescription
     */
    appointmentId?: string;
    /**
     * 
     * @type {string}
     * @memberof Prescription
     */
    diagnosis: string;
    /**
     * 
     * @type {Array<PrescriptionMedications>}
     * @memberof Prescription
     */
    medications: Array<PrescriptionMedications>;
    /**
     * 
     * @type {string}
     * @memberof Prescription
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof Prescription
     */
    issuedAt: string;
    /**
     * 
     * @type {string}
     * @memberof Prescription
     */
    validUntil?: string;
    /**
     * 
     * @type {string}
     * @memberof Prescription
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof Prescription
     */
    updatedAt: string;
}

export function PrescriptionFromJSON(json: any): Prescription {
    return PrescriptionFromJSONTyped(json, false);
}

export function PrescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Prescription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'patientId': json['patient_id'],
        'doctorId': json['doctor_id'],
        'appointmentId': !exists(json, 'appointment_id') ? undefined : json['appointment_id'],
        'diagnosis': json['diagnosis'],
        'medications': ((json['medications'] as Array<any>).map(PrescriptionMedicationsFromJSON)),
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'issuedAt': json['issued_at'],
        'validUntil': !exists(json, 'valid_until') ? undefined : json['valid_until'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function PrescriptionToJSON(value?: Prescription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'patient_id': value.patientId,
        'doctor_id': value.doctorId,
        'appointment_id': value.appointmentId,
        'diagnosis': value.diagnosis,
        'medications': ((value.medications as Array<any>).map(PrescriptionMedicationsToJSON)),
        'notes': value.notes,
        'issued_at': value.issuedAt,
        'valid_until': value.validUntil,
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
    };
}

