/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignupInput
 */
export interface SignupInput {
    /**
     * 
     * @type {string}
     * @memberof SignupInput
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof SignupInput
     */
    birthdate: string;
    /**
     * 
     * @type {string}
     * @memberof SignupInput
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignupInput
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof SignupInput
     */
    phone?: string;
}

export function SignupInputFromJSON(json: any): SignupInput {
    return SignupInputFromJSONTyped(json, false);
}

export function SignupInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fullName': json['fullName'],
        'birthdate': json['birthdate'],
        'email': json['email'],
        'password': json['password'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
    };
}

export function SignupInputToJSON(value?: SignupInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fullName': value.fullName,
        'birthdate': value.birthdate,
        'email': value.email,
        'password': value.password,
        'phone': value.phone,
    };
}

