/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DoctorProfileAvailability,
    DoctorProfileAvailabilityFromJSON,
    DoctorProfileAvailabilityFromJSONTyped,
    DoctorProfileAvailabilityToJSON,
} from './DoctorProfileAvailability';
import {
    DoctorProfileLocation,
    DoctorProfileLocationFromJSON,
    DoctorProfileLocationFromJSONTyped,
    DoctorProfileLocationToJSON,
} from './DoctorProfileLocation';

/**
 * 
 * @export
 * @interface UpdateDoctorProfileDto
 */
export interface UpdateDoctorProfileDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateDoctorProfileDto
     */
    specialization?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDoctorProfileDto
     */
    licenseNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDoctorProfileDto
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDoctorProfileDto
     */
    bio?: string;
    /**
     * 
     * @type {DoctorProfileLocation}
     * @memberof UpdateDoctorProfileDto
     */
    location?: DoctorProfileLocation;
    /**
     * 
     * @type {Array<DoctorProfileAvailability>}
     * @memberof UpdateDoctorProfileDto
     */
    availability?: Array<DoctorProfileAvailability>;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateDoctorProfileDto
     */
    isAvailableForEmergency?: boolean;
}

export function UpdateDoctorProfileDtoFromJSON(json: any): UpdateDoctorProfileDto {
    return UpdateDoctorProfileDtoFromJSONTyped(json, false);
}

export function UpdateDoctorProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDoctorProfileDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'specialization': !exists(json, 'specialization') ? undefined : json['specialization'],
        'licenseNumber': !exists(json, 'license_number') ? undefined : json['license_number'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'bio': !exists(json, 'bio') ? undefined : json['bio'],
        'location': !exists(json, 'location') ? undefined : DoctorProfileLocationFromJSON(json['location']),
        'availability': !exists(json, 'availability') ? undefined : ((json['availability'] as Array<any>).map(DoctorProfileAvailabilityFromJSON)),
        'isAvailableForEmergency': !exists(json, 'is_available_for_emergency') ? undefined : json['is_available_for_emergency'],
    };
}

export function UpdateDoctorProfileDtoToJSON(value?: UpdateDoctorProfileDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'specialization': value.specialization,
        'license_number': value.licenseNumber,
        'phone': value.phone,
        'bio': value.bio,
        'location': DoctorProfileLocationToJSON(value.location),
        'availability': value.availability === undefined ? undefined : ((value.availability as Array<any>).map(DoctorProfileAvailabilityToJSON)),
        'is_available_for_emergency': value.isAvailableForEmergency,
    };
}

