/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMedicineDto
 */
export interface UpdateMedicineDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicineDto
     */
    patientId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicineDto
     */
    medicineName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicineDto
     */
    medicineType?: UpdateMedicineDtoMedicineTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicineDto
     */
    dosage?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicineDto
     */
    strength?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicineDto
     */
    frequency?: UpdateMedicineDtoFrequencyEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateMedicineDto
     */
    timing?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicineDto
     */
    startDate?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicineDto
     */
    endDate?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateMedicineDto
     */
    reminderEnabled?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateMedicineDto
     */
    reminderTimes?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof UpdateMedicineDto
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicineDto
     */
    doctorName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicineDto
     */
    prescriptionNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicineDto
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMedicineDto
     */
    status?: UpdateMedicineDtoStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum UpdateMedicineDtoMedicineTypeEnum {
    Tablet = 'Tablet',
    Capsule = 'Capsule',
    Syrup = 'Syrup',
    Injection = 'Injection',
    Drops = 'Drops',
    Cream = 'Cream',
    Other = 'Other'
}/**
* @export
* @enum {string}
*/
export enum UpdateMedicineDtoFrequencyEnum {
    OnceDaily = 'Once Daily',
    TwiceDaily = 'Twice Daily',
    ThreeTimesDaily = 'Three Times Daily',
    FourTimesDaily = 'Four Times Daily',
    Every6Hours = 'Every 6 Hours',
    Weekly = 'Weekly',
    Custom = 'Custom'
}/**
* @export
* @enum {string}
*/
export enum UpdateMedicineDtoStatusEnum {
    Active = 'Active',
    Completed = 'Completed',
    Upcoming = 'Upcoming',
    Expired = 'Expired'
}

export function UpdateMedicineDtoFromJSON(json: any): UpdateMedicineDto {
    return UpdateMedicineDtoFromJSONTyped(json, false);
}

export function UpdateMedicineDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMedicineDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientId': !exists(json, 'patient_id') ? undefined : json['patient_id'],
        'medicineName': !exists(json, 'medicine_name') ? undefined : json['medicine_name'],
        'medicineType': !exists(json, 'medicine_type') ? undefined : json['medicine_type'],
        'dosage': !exists(json, 'dosage') ? undefined : json['dosage'],
        'strength': !exists(json, 'strength') ? undefined : json['strength'],
        'frequency': !exists(json, 'frequency') ? undefined : json['frequency'],
        'timing': !exists(json, 'timing') ? undefined : json['timing'],
        'startDate': !exists(json, 'start_date') ? undefined : json['start_date'],
        'endDate': !exists(json, 'end_date') ? undefined : json['end_date'],
        'reminderEnabled': !exists(json, 'reminder_enabled') ? undefined : json['reminder_enabled'],
        'reminderTimes': !exists(json, 'reminder_times') ? undefined : json['reminder_times'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
        'doctorName': !exists(json, 'doctor_name') ? undefined : json['doctor_name'],
        'prescriptionNumber': !exists(json, 'prescription_number') ? undefined : json['prescription_number'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function UpdateMedicineDtoToJSON(value?: UpdateMedicineDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patient_id': value.patientId,
        'medicine_name': value.medicineName,
        'medicine_type': value.medicineType,
        'dosage': value.dosage,
        'strength': value.strength,
        'frequency': value.frequency,
        'timing': value.timing,
        'start_date': value.startDate,
        'end_date': value.endDate,
        'reminder_enabled': value.reminderEnabled,
        'reminder_times': value.reminderTimes,
        'quantity': value.quantity,
        'doctor_name': value.doctorName,
        'prescription_number': value.prescriptionNumber,
        'notes': value.notes,
        'status': value.status,
    };
}

