/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DoctorProfileAvailability,
    DoctorProfileAvailabilityFromJSON,
    DoctorProfileAvailabilityFromJSONTyped,
    DoctorProfileAvailabilityToJSON,
} from './DoctorProfileAvailability';

/**
 * 
 * @export
 * @interface UpdateAvailabilityDto
 */
export interface UpdateAvailabilityDto {
    /**
     * 
     * @type {Array<DoctorProfileAvailability>}
     * @memberof UpdateAvailabilityDto
     */
    availability: Array<DoctorProfileAvailability>;
}

export function UpdateAvailabilityDtoFromJSON(json: any): UpdateAvailabilityDto {
    return UpdateAvailabilityDtoFromJSONTyped(json, false);
}

export function UpdateAvailabilityDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAvailabilityDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'availability': ((json['availability'] as Array<any>).map(DoctorProfileAvailabilityFromJSON)),
    };
}

export function UpdateAvailabilityDtoToJSON(value?: UpdateAvailabilityDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'availability': ((value.availability as Array<any>).map(DoctorProfileAvailabilityToJSON)),
    };
}

