/* tslint:disable */
/* eslint-disable */
/**
 * Elderly API
 * API documentation for the Elderly project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    birthdate: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    passwordHash: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    role?: UserRoleEnum;
}

/**
* @export
* @enum {string}
*/
export enum UserRoleEnum {
    Normal = 'normal',
    Family = 'family',
    Doctor = 'doctor'
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'fullName': json['fullName'],
        'birthdate': json['birthdate'],
        'email': json['email'],
        'passwordHash': json['passwordHash'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'createdAt': json['createdAt'],
        'role': !exists(json, 'role') ? undefined : json['role'],
    };
}

export function UserToJSON(value?: User | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'fullName': value.fullName,
        'birthdate': value.birthdate,
        'email': value.email,
        'passwordHash': value.passwordHash,
        'phone': value.phone,
        'createdAt': value.createdAt,
        'role': value.role,
    };
}

